In [72]:
df_clean.to_csv("../Data/Cleaned/instagram_creator_analysis.csv",index = False)

In [70]:
df_clean.shape

(29999, 25)

In [69]:
df_clean[["engagement_rate","engagement_rate_calc"]].head(10)

   engagement_rate  engagement_rate_calc
0           0.0385              5.546568
1           0.0663              7.354717
2           0.0531              8.480781
3           0.0309              3.406326
4           0.0221              3.514019
5           0.0516              6.709145
6           0.0584              8.927860
7           0.0162              2.040816
8           0.0657              8.421053
9           0.0401              5.475638

In [68]:
difference.describe()

count    29999.000000
mean         5.574602
std          3.104903
min          0.000000
25%          3.222784
50%          5.426729
75%          7.642539
max         29.871141
dtype: float64

In [67]:
difference = df_clean["engagement_rate_calc"] - df["engagement_rate"]

In [66]:
df_clean.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label,total_engagement,engagement_rate_calc
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,34,4327,6230,0.0385,899,100,7,medium,240,5.546568
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,68,7451,8268,0.0663,805,122,5,viral,548,7.354717
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,22,1639,2616,0.0531,758,115,8,high,139,8.480781
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,2877,3171,0.0309,402,115,7,medium,98,3.406326
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,21,5350,8503,0.0221,155,112,9,low,188,3.514019

In [65]:
df_clean[["total_engagement","engagement_rate","engagement_rate_calc"]].head()

   total_engagement  engagement_rate  engagement_rate_calc
0               240           0.0385              5.546568
1               548           0.0663              7.354717
2               139           0.0531              8.480781
3                98           0.0309              3.406326
4               188           0.0221              3.514019

In [64]:
df_clean["engagement_rate_calc"] = (df_clean["total_engagement"] / df_clean["reach"]) * 100

In [63]:
df_clean["total_engagement"].describe()

count    29999.000000
mean       353.119404
std        388.131521
min          0.000000
25%        128.000000
50%        243.000000
75%        444.000000
max      13029.000000
Name: total_engagement, dtype: float64

In [62]:
df_clean[["likes","comments","shares","saves","total_engagement"]].head()

   likes  comments  shares  saves  total_engagement
0    194         5       7     34               240
1    449        10      21     68               548
2    114         2       1     22               139
3     91         0       7      0                98
4    154         8       5     21               188

In [61]:
df_clean["total_engagement"].head()

0    240
1    548
2    139
3     98
4    188
Name: total_engagement, dtype: int64

In [60]:
df_clean["total_engagement"] = df_clean["likes"] + df_clean["comments"] + df_clean["saves"] + df_clean["shares"]

In [59]:
df_clean.head

<bound method NDFrame.head of          post_id  account_id account_type  follower_count media_type  \
0      IG0000001           7        brand            3551       reel
1      IG0000002          20      creator           31095      image
2      IG0000003          15        brand            8167       reel
3      IG0000004          11      creator            9044   carousel
4      IG0000005           8      creator           15986       reel
...          ...         ...          ...             ...        ...
29994  IG0029995           5        brand           10739   carousel
29995  IG0029996           3        brand           10018      image
29996  IG0029997          18      creator            7486      image
29997  IG0029998           6      creator           10034   carousel
29998  IG0029999           9      creator            6916      image

      content_category traffic_source  has_call_to_action       post_datetime  \
0           Technology      Home Feed                   1 2024-11-30 06:00:00
1              Fitness       Hashtags                   1 2025-08-15 15:00:00
2               Beauty     Reels Feed                   0 2025-09-11 16:00:00
3                Music       External                   0 2025-09-18 03:00:00
4           Technology        Profile                   0 2025-03-21 09:00:00
...                ...            ...                 ...                 ...
29994           Travel     Reels Feed                   0 2024-12-18 10:00:00
29995           Beauty       Hashtags                   0 2025-05-05 15:00:00
29996      Photography        Explore                   1 2025-05-26 10:00:00
29997       Technology        Explore                   1 2025-08-02 19:00:00
29998       Technology        Explore                   1 2025-04-15 20:00:00

       post_date  ...  comments shares  saves  reach  impressions  \
0     2024-11-30  ...         5      7     34   4327         6230
1     2025-08-15  ...        10     21     68   7451         8268
2     2025-09-11  ...         2      1     22   1639         2616
3     2025-09-18  ...         0      7      0   2877         3171
4     2025-03-21  ...         8      5     21   5350         8503
...          ...  ...       ...    ...    ...    ...          ...
29994 2024-12-18  ...         1      2      5   1564         2493
29995 2025-05-05  ...         2      1      7   2042         2492
29996 2025-05-26  ...        10     16     59   5887         7528
29997 2025-08-02  ...         3      0     19   5372         6312
29998 2025-04-15  ...         1      1      5   4019         5678

       engagement_rate  followers_gained  caption_length  hashtags_count  \
0               0.0385               899             100               7
1               0.0663               805             122               5
2               0.0531               758             115               8
3               0.0309               402             115               7
4               0.0221               155             112               9
...                ...               ...             ...             ...
29994           0.0032               124             127               8
29995           0.0209               310             114              12
29996           0.0558               223             115               4
29997           0.0333               978             124               4
29998           0.0100               272             126              11

       performance_bucket_label
0                        medium
1                         viral
2                          high
3                        medium
4                           low
...                         ...
29994                       low
29995                       low
29996                      high
29997                    medium
29998                       low

[29999 rows x 23 columns]>

In [58]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   post_id                   29999 non-null  str
 1   account_id                29999 non-null  int64
 2   account_type              29999 non-null  str
 3   follower_count            29999 non-null  int64
 4   media_type                29999 non-null  str
 5   content_category          29999 non-null  str
 6   traffic_source            29999 non-null  str
 7   has_call_to_action        29999 non-null  int64
 8   post_datetime             29999 non-null  datetime64[us]
 9   post_date                 29999 non-null  datetime64[us]
 10  post_hour                 29999 non-null  int64
 11  day_of_week               29999 non-null  str
 12  likes                     29999 non-null  int64
 13  comments                  29999 non-null  int64
 14  shares                    29999 non-null  int64
 15  saves                     29999 non-null  int64
 16  reach                     29999 non-null  int64
 17  impressions               29999 non-null  int64
 18  engagement_rate           29999 non-null  float64
 19  followers_gained          29999 non-null  int64
 20  caption_length            29999 non-null  int64
 21  hashtags_count            29999 non-null  int64
 22  performance_bucket_label  29999 non-null  str
dtypes: datetime64[us](2), float64(1), int64(13), str(7)
memory usage: 5.3 MB

In [57]:
df_clean[["post_date","post_datetime"]].isnull().sum()

post_date        0
post_datetime    0
dtype: int64

In [56]:
df_clean[["post_date","post_datetime"]].dtypes

post_date        datetime64[us]
post_datetime    datetime64[us]
dtype: object

In [55]:
df_clean["post_date"] = pd.to_datetime(df_clean["post_date"],errors="coerce")
df_clean["post_datetime"] = pd.to_datetime(df_clean["post_datetime"],errors="coerce")

In [54]:
df_clean.columns

Index(['post_id', 'account_id', 'account_type', 'follower_count', 'media_type',
       'content_category', 'traffic_source', 'has_call_to_action',
       'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes',
       'comments', 'shares', 'saves', 'reach', 'impressions',
       'engagement_rate', 'followers_gained', 'caption_length',
       'hashtags_count', 'performance_bucket_label'],
      dtype='str')

In [53]:
df_clean.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,10,21,68,7451,8268,0.0663,805,122,5,viral
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,2,1,22,1639,2616,0.0531,758,115,8,high
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,7,0,2877,3171,0.0309,402,115,7,medium
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,8,5,21,5350,8503,0.0221,155,112,9,low

In [52]:
df.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,10,21,68,7451,8268,0.0663,805,122,5,viral
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,2,1,22,1639,2616,0.0531,758,115,8,high
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,7,0,2877,3171,0.0309,402,115,7,medium
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,8,5,21,5350,8503,0.0221,155,112,9,low

In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv("../Data/Raw/Dataset A.csv")

df_clean = df.copy()

In [51]:
df_clean.columns

Index(['post_id', 'account_id', 'account_type', 'follower_count', 'media_type',
       'content_category', 'traffic_source', 'has_call_to_action',
       'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes',
       'comments', 'shares', 'saves', 'reach', 'impressions',
       'engagement_rate', 'followers_gained', 'caption_length',
       'hashtags_count', 'performance_bucket_label'],
      dtype='str')

In [50]:
df_clean.columns = (df_clean.columns
                    .str.strip()
                    .str.lower()
                    .str.replace(" ","_"))

In [49]:
df_clean.shape

(29999, 23)

In [48]:
df_clean = df.copy()

In [13]:
print(df["post_date"].head())
print(df["post_datetime"].head())

0    2024-11-30
1    2025-08-15
2    2025-09-11
3    2025-09-18
4    2025-03-21
Name: post_date, dtype: str
0    2024-11-30 06:00:00
1    2025-08-15 15:00:00
2    2025-09-11 16:00:00
3    2025-09-18 03:00:00
4    2025-03-21 09:00:00
Name: post_datetime, dtype: str

In [14]:
df["has_call_to_action"].value_counts()

has_call_to_action
0    19536
1    10463
Name: count, dtype: int64

In [15]:
print("Account Types:")
print(df["account_type"].value_counts())

print("Media Types:")
print(df["media_type"].value_counts())

print("Content Categories:")
print(df["content_category"].value_counts())

print("Traffic Sources:")
print(df["traffic_source"].value_counts())

print("Performance Bucket:")
print(df["performance_bucket_label"].value_counts())

Account Types:
account_type
creator    20944
brand       9055
Name: count, dtype: int64
Media Types:
media_type
image       11927
carousel    10627
reel         7445
Name: count, dtype: int64
Content Categories:
content_category
Photography    3035
Fashion        3034
Technology     3025
Lifestyle      3017
Food           3010
Fitness        3004
Music          3003
Travel         2968
Beauty         2953
Comedy         2950
Name: count, dtype: int64
Traffic Sources:
traffic_source
Home Feed     5069
Hashtags      5063
Reels Feed    5026
External      5005
Profile       4962
Explore       4874
Name: count, dtype: int64
Performance Bucket:
performance_bucket_label
viral     7500
high      7500
low       7500
medium    7499
Name: count, dtype: int64

In [16]:
numeric_cols = ["follower_count","likes","comments","shares","saves","reach","impressions","followers_gained","caption_length","hashtags_count"]
(df[numeric_cols]<0).sum()

follower_count      0
likes               0
comments            0
shares              0
saves               0
reach               0
impressions         0
followers_gained    0
caption_length      0
hashtags_count      0
dtype: int64

In [17]:
df["post_id"].duplicated().sum()

np.int64(0)

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.isnull().sum()

post_id                     0
account_id                  0
account_type                0
follower_count              0
media_type                  0
content_category            0
traffic_source              0
has_call_to_action          0
post_datetime               0
post_date                   0
post_hour                   0
day_of_week                 0
likes                       0
comments                    0
shares                      0
saves                       0
reach                       0
impressions                 0
engagement_rate             0
followers_gained            0
caption_length              0
hashtags_count              0
performance_bucket_label    0
dtype: int64

In [20]:
df.isnull().sum()

post_id                     0
account_id                  0
account_type                0
follower_count              0
media_type                  0
content_category            0
traffic_source              0
has_call_to_action          0
post_datetime               0
post_date                   0
post_hour                   0
day_of_week                 0
likes                       0
comments                    0
shares                      0
saves                       0
reach                       0
impressions                 0
engagement_rate             0
followers_gained            0
caption_length              0
hashtags_count              0
performance_bucket_label    0
dtype: int64

In [21]:
df.dtypes

post_id                         str
account_id                    int64
account_type                    str
follower_count                int64
media_type                      str
content_category                str
traffic_source                  str
has_call_to_action            int64
post_datetime                   str
post_date                       str
post_hour                     int64
day_of_week                     str
likes                         int64
comments                      int64
shares                        int64
saves                         int64
reach                         int64
impressions                   int64
engagement_rate             float64
followers_gained              int64
caption_length                int64
hashtags_count                int64
performance_bucket_label        str
dtype: object

In [22]:
df.describe()

,account_id,follower_count,has_call_to_action,post_hour,likes,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count
count,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000
mean,10.567819,10278.305477,0.348778,11.499417,287.653588,8.521917,14.426614,42.517284,6272.475449,8466.952498,0.042107,502.152805,120.081169,7.987933
std,5.763952,6691.862669,0.476592,6.900587,317.647682,10.116505,16.420899,47.808844,4985.877059,6825.900355,0.024095,290.364038,11.009108,2.828130
min,1.000000,3083.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,268.000000,327.000000,0.000000,0.000000,70.000000,0.000000
25%,6.000000,5824.000000,0.000000,6.000000,104.000000,3.000000,5.000000,15.000000,3058.000000,4102.000000,0.024000,251.000000,113.000000,6.000000
50%,11.000000,9044.000000,0.000000,12.000000,199.000000,6.000000,10.000000,29.000000,4913.000000,6595.000000,0.040600,501.000000,120.000000,8.000000
75%,16.000000,10739.000000,1.000000,17.000000,363.000000,11.000000,19.000000,54.000000,7863.000000,10620.500000,0.057000,755.000000,127.000000,10.000000
max,20.000000,31095.000000,1.000000,23.000000,10632.000000,339.000000,516.000000,1542.000000,73339.000000,105203.000000,0.271000,1000.000000,166.000000,21.000000

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   post_id                   29999 non-null  str
 1   account_id                29999 non-null  int64
 2   account_type              29999 non-null  str
 3   follower_count            29999 non-null  int64
 4   media_type                29999 non-null  str
 5   content_category          29999 non-null  str
 6   traffic_source            29999 non-null  str
 7   has_call_to_action        29999 non-null  int64
 8   post_datetime             29999 non-null  str
 9   post_date                 29999 non-null  str
 10  post_hour                 29999 non-null  int64
 11  day_of_week               29999 non-null  str
 12  likes                     29999 non-null  int64
 13  comments                  29999 non-null  int64
 14  shares                    29999 non-null  int64
 15  saves                     29999 non-null  int64
 16  reach                     29999 non-null  int64
 17  impressions               29999 non-null  int64
 18  engagement_rate           29999 non-null  float64
 19  followers_gained          29999 non-null  int64
 20  caption_length            29999 non-null  int64
 21  hashtags_count            29999 non-null  int64
 22  performance_bucket_label  29999 non-null  str
dtypes: float64(1), int64(13), str(9)
memory usage: 5.3 MB

In [24]:
df.columns

Index(['post_id', 'account_id', 'account_type', 'follower_count', 'media_type',
       'content_category', 'traffic_source', 'has_call_to_action',
       'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes',
       'comments', 'shares', 'saves', 'reach', 'impressions',
       'engagement_rate', 'followers_gained', 'caption_length',
       'hashtags_count', 'performance_bucket_label'],
      dtype='str')

In [25]:
df.shape

(29999, 23)

In [26]:
df.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,10,21,68,7451,8268,0.0663,805,122,5,viral
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,2,1,22,1639,2616,0.0531,758,115,8,high
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,7,0,2877,3171,0.0309,402,115,7,medium
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,8,5,21,5350,8503,0.0221,155,112,9,low

In [27]:
df = pd.read_csv("../Data/Raw/Dataset A.csv")

In [28]:
import numpy as np
import pandas as pd